# Generated by Django 6.0 on 2025-12-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('event', 'email')},
        ),
    ]
