# Generated by Django 6.0 on 2025-12-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_participant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
    ]
